###########################
## Markdown Linter rules ##
###########################

# See below for the full list of rules
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->

# Allow inline HTML
MD033: false

# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one
