# Terrascan configuration file
# https://github.com/accurics/terrascan/blob/master/config/terrascan.toml

[rules]
# The following are resolved, but Terrascan is showing a violation:
# AWS.SQS.NetworkSecurity.High.0570
# The remainder are not impacted by the current configuration.
skip-rules = [
  'AC_AWS_0163',
  'AC_AWS_0366',
  'AC_AWS_0369',
  'AC_AWS_0485',
  'AC_AWS_0486',
]
