#!/bin/bash
WORKSPACE=$(pwd)

# Get the S3 bucket ARN from the Terraform outputs
cd "$WORKSPACE/tf/"
BUCKET_ARN=$(terraform output -raw s3_bucket_arn)
echo "Received bucket ARN: $BUCKET_ARN"
BUCKET_NAME=$(echo $BUCKET_ARN | cut -d':' -f6)

# List the contents of the bucket
OBJECTS=$(aws s3 ls s3://$BUCKET_NAME/ --recursive | wc -l)
echo "Object count: $OBJECTS"

# Download the contents of the bucket
mkdir -p "$WORKSPACE/output/"
aws s3 sync s3://$BUCKET_NAME/ "$WORKSPACE/output/"

OBJECT_COUNT=$(ls -la $WORKSPACE/output/ | wc -l)
echo "Downloaded: $OBJECT_COUNT files."