#!/bin/bash

cd tf/ || $(echo "Please run from the root of the repository" && exit)

# Deploy the Terraform
terraform init
# terraform plan -var-file ../settings.json
terraform apply -auto-approve -var-file ../settings.json

# Get the Lambda function ARN from the Terraform outputs
FUNCTION_ARN=$(terraform output -raw lambda_function_arn)
echo "Received function ARN: $FUNCTION_ARN"

# Read data.json, and invoke the function with each data entry as input
for entry in $(< ../input.json jq -c -r '.[] | @base64'); do
  echo "Invoking with payload: $entry"

  aws lambda invoke \
    --function-name "$FUNCTION_ARN" \
    --invocation-type "Event" \
    --payload $entry /dev/null 2>&1
done
