#!/bin/bash
WORKSPACE=$(pwd)

# Get the user data for the consumer instances
cd "$WORKSPACE/src/" || (echo "Please run from the root of the repository" && exit)
zip ../consumer.zip -r consumer/ utils/ package.json

# Set the user data in the Terraform variables
export TF_VAR_aws_spot_instance_user_data_base64=$(cat ../consumer.zip | base64)

# Get the S3 bucket ARN from the Terraform outputs
cd "$WORKSPACE/tf/"
BUCKET_ARN=$(terraform output -raw s3_bucket_arn)
echo "Received bucket ARN: $BUCKET_ARN"
BUCKET_NAME=$(echo $BUCKET_ARN | cut -d':' -f6)

# List the contents of the bucket
OBJECTS=$(aws s3 ls s3://$BUCKET_NAME/ --recursive | wc -l)
echo "Object count: $OBJECTS"

# Download the contents of the bucket
mkdir -p "$WORKSPACE/output/"
aws s3 sync s3://$BUCKET_NAME/ "$WORKSPACE/output/"
echo "Bucket contents copied to $WORKSPACE/output/"

# Delete temporary files
rm -f ../producer.zip
rm -f ../consumer.zip

read -p "WARNING: Do you want to delete **all** the AWS resources? (Y/N) " -r

if [[ $REPLY =~ ^[Yy]$ ]]
then

  # Destroy the Terraform
  cd "$WORKSPACE/tf/"
  terraform destroy -auto-approve -var-file ../settings.json

  echo "Resources destroyed!"
fi

echo "Complete!"
