# Perform CI tests on Node.js and Terraform code in this repository. This
# workflow is triggered on pushes and pull requests.
name: Continuous Integration

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  statuses: write

env:
  NODE_DIRECTORY: src/
  TERRAFORM_DIRECTORY: tf/
  TFLINT_CONFIG_PATH: .github/linters/.tflint.hcl

jobs:
  # Perform CI tests on Node.js code in this repository.
  node-ci:
    name: Node.js CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Check Format
        id: format-check
        run: npm run format:check

      - name: Lint
        id: lint
        run: npm run lint

      - name: Test
        id: test
        run: npm run ci-test

  # Perform CI and security tests on Terraform code in this repository.
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_DIRECTORY }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          terraform init -no-color
          tflint --init -c '${{ github.workspace }}/${{ env.TFLINT_CONFIG_PATH }}' --no-color

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Format
        id: format
        run: terraform fmt -check -recursive

      - name: Terraform Lint
        id: lint
        run: |
          tflint -f compact -c '${{ github.workspace }}/${{ env.TFLINT_CONFIG_PATH }}' --recursive --no-color

      - name: Terraform Security
        id: tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory: ${{ env.TERRAFORM_DIRECTORY }}
          sarif_file: tfsec.sarif
          full_repo_scan: true

      - name: Upload SARIF
        id: upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color -lock=false

      # - if: ${{ steps.plan.outcome == 'failure' }}
      #   name: Terraform Plan Failure
      #   id: plan-failure
      #   run: exit 1
